### PR TITLE
tests

### PR DESCRIPTION
**Pull request by venosov**

### CODE REVIEW

**Comment by codependent** [comment]
I'd suggest two minor changes to merge this PR:

1. Replace the json Strings for multiline Strings, which would greatly improve the clarity.
2. Static imports for Assertions and Mockito.

**Comment by venosov** [comment]
Unlike Java, Kotlin does not have a separate "import static" syntax; all of these declarations are imported using the regular import keyword.

**Comment by codependent** [comment]
It's true that the import static syntax is not available, but you can import class members:

```
import org.junit.jupiter.api.Assertions.*
...
assertEquals(2, savedApps.size)
```

**Comment by venosov** [comment]
ok ok, done!

**Comment by codependent** [comment]
I appreciate it Venosov ;)

**Pull request merged**
